version: "3"

services:
  mongodb:
    image: user-mongo
    restart: always
    networks: 
      - building
  
  go:
    depends_on: 
      - mongodb
    image: witthawat0572/building-docker
    restart: always
    networks: 
      - building
    ports: 
      - 3000:3000
    
networks: 
  building: 