---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: building-system
spec:
  replicas: 5
  selector:
    matchLabels:
      name: building-system
  template:
    metadata:
      labels:
        name: building-system
    spec:
      containers:
      - name: application
        image: witthawat0572/building-system
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: bul-system-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    name: building-system