apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-standalone
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        selector: mongodb-standalone
    spec:
      containers:
      - name: mongodb-standalone
        image: mongo
        env:
          - name: MONGO_INITDB_ROOT_USERNAME_FILE
            value: /etc/k8-secret-etneca/admin/MONGO_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD_FILE
            value: /etc/k8-secret-etneca/admin/MONGO_ROOT_PASSWORD
        volumeMounts:
        - name: k8-secret-etneca
          mountPath: /etc/k8-secret-etneca
          readOnly: true
      nodeSelector:
        kubernetes.io/hostname: pool-kub-hkt-8npim
      volumes:
      - name: k8-secret-etneca
        secret:
          secretName: k8-secret-etneca
          items:
          - key: MONGO_ROOT_USERNAME
            path: admin/MONGO_ROOT_USERNAME
            mode: 0444
          - key: MONGO_ROOT_PASSWORD
            path: admin/MONGO_ROOT_PASSWORD
            mode: 0444
---