---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: building-login
spec:
  replicas: 5
  selector:
    matchLabels:
      name: building-login
  template:
    metadata:
      labels:
        name: building-login
    spec:
      containers:
      - name: application
        image: witthawat0572/building-login
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000